version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - soukBackend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: souk-backend
    ports:
      - "2025:2025"
    networks:
      - soukBackend
    depends_on:
      - redis
    command: npm run start

networks:
  soukBackend:
    driver: bridge
